### PR TITLE
feat(tangle-dapp): Withdraw Unbonded Token Flow, UI Changes & Minor Fixes

### LINKED ISSUE #1927: [TASK] Add withdraw unbonded tokens flow
### Overview

When users unbond a portion or all of their staked amount, these tokens will become available for withdrawal after a certain number of eras. We should implement this flow.

The current limitation to implementing this flow is the time it takes to reach the withdrawal era. We need to discuss with the team how to address and implement this feature effectively.

### Polkadot apps

CleanShot 2024-01-02 at 06 36 28

### Precompile function

CleanShot 2024-01-02 at 06 41 42

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Adds withdraw unbonded tokens flow.
- Removes account address displays from all the flows.
- Updates all flows related container's width and padding.
- Adds unbonding and unbonded token balance in rebond flow.

### Note

- When the user successfully withdraws the unbonded tokens, the wallet balance is not updated in real-time. The user has to reconnect the wallet to the dapp to see the balance change. This is a major UX issue. We're using viem to fetch the wallet balance, and I've spent some time trying to find solutions—polling, listening to token balance changes, etc. Unfortunately, I could not find anything. I'll keep looking and address this in future PRs. Issue created here #1943 

### Proposed area of change

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes #1927 

### Screen Recordings

https://github.com/webb-tools/webb-dapp/assets/53374218/5c85e231-eb0f-41b9-85e9-23a7f3afb608

https://github.com/webb-tools/webb-dapp/assets/53374218/e5af524e-e878-493f-ae49-dc0f565231a8

CleanShot 2024-01-10 at 18 50 27

CleanShot 2024-01-10 at 19 01 29

### CODE REVIEW

File: apps/tangle-dapp/components/BondedTokensBalanceInfo/BondedTokensBalanceInfo.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+export const BondedTokensBalanceInfo: FC<BondedTokensBalanceInfoProps> = ({
+  type,
+  value,
+}) => (
+  <div className="flex items-center justify-between">
+    <div className="flex gap-1 items-center">
+      {type === 'unbonded' ? <LockUnlockLineIcon /> : <TimeLineIcon />}
+
+      {type === 'unbonded' ? (
```
Comment (vutuanlinh2k2) [inline apps/tangle-dapp/components/BondedTokensBalanceInfo/BondedTokensBalanceInfo.tsx:15]: this can be changed to 
```
<Typography variant="body1" fw="normal">
  {type === 'unbonded' ? 'Unbonded:' : 'Unbonding:'}
</Typography>
```

File: libs/dapp-config/src/chains/evm/index.tsx [hunk 2]
```diff
@@ -430,34 +431,4 @@ export const chainsConfig: Record<number, ChainConfig> = {
         }
       : undefined,
   } satisfies ChainConfig,
-
-  [PresetTypedChainId.LocalTangleTestnet]: {
```
Comment (vutuanlinh2k2) [inline libs/dapp-config/src/chains/evm/index.tsx:434]: Why did you delete the LocalTangleTestnet here?

File: libs/dapp-types/src/ChainId.ts [hunk 3]
```diff
@@ -121,11 +121,6 @@ export enum PresetTypedChainId {
     ChainType.EVM,
     EVMChainId.TangleTestnet
   ),
-
-  LocalTangleTestnet = calculateTypedChainId(
```
Comment (vutuanlinh2k2) [inline libs/dapp-types/src/ChainId.ts:125]: [Same](https://github.com/webb-tools/webb-dapp/pull/1944/files#r1448712661)

File: libs/dapp-types/src/EVMChainId.ts [hunk 4]
```diff
@@ -27,9 +27,6 @@ export enum EVMChainId {
   HermesLocalnet = 5001,
   AthenaLocalnet = 5002,
   DemeterLocalnet = 5003,
-
-  /** Local Tangle */
-  LocalTangleTestnet = 3799,
```
Comment (vutuanlinh2k2) [inline libs/dapp-types/src/EVMChainId.ts:32]: [Same](https://github.com/webb-tools/webb-dapp/pull/1944/files#r1448712661)

**Comment by devpavan04** [comment]
@vutuanlinh2k2, it was removed because it's a copy of `[PresetTypedChainId.TangleTestnet]`. Additionally, `[PresetTypedChainId.TangleTestnet]` is configured in a way that it returns a local endpoint and a testnet RPC endpoint based on the `USING_LOCAL_TANGLE` environment variable.

**Comment by devpavan04** [comment]
### Fixes/Changes

CleanShot 2024-01-11 at 13 54 55

CleanShot 2024-01-11 at 13 55 19

CleanShot 2024-01-11 at 13 55 33

**Comment by devpavan04** [comment]
🚧 **WIP**: This PR will be ready for review once I push `inflation` fix.

**Comment by devpavan04** [comment]
### Preview

https://deploy-preview-1944--tangle-dapp.netlify.app/
