### PR TITLE
perf(tangle-dapp): Cache nominations & payouts in local storage & UI fixes

### LINKED ISSUE #2022: [CHECKLIST] Tangle Nominate (Staking) Page Audit
## Checklist
Below are the checklist items based on audit session with @yurixander for https://app.tangle.tools/ for Nominate (EVM Staking) Page. 

- [x] Staking Overview Pills:
  - Prevent squishing at certain browser widths by allowing text to wrap.
  - Implement a minimum width for the staking overview pills to avoid text overflow.
  Image

- [x] Total Staked/Unbonding Containers:
  - Set a minimum width to prevent them from becoming too small.
  - Ensure buttons do not crowd each other; expand into full width as needed.
Image

- [x] Table Components:
  - Ensure the scrollbar is visible at desktop viewports when content exceeds visible area.
  - Empty Table States: Add extra padding at the top and bottom for 'Ready to explore nominations' & 'No validators in waiting' states.

### LINKED ISSUE #2104: [TASK] Nomination Page Links / Cosmetic Updates
### Button Link Updates:
- [x] Learn More: https://docs.tangle.tools/docs/use/staking-intro/
- [x] Get TNT: https://discord.com/channels/833784453251596298/1183826417625075753
- [x] Join Community: https://www.tangle.tools/community

### Cosmetic Updates:
- [x] Fix buttons alignment, check all viewports/dimensions.
Image
- [x] Remove the word `Staking` from `Staking Overview`; just `Overview` is sufficient.
Image

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Nominations and payouts data is cached in local storage to improve data load time.
- Adds padding in key stats container to avoid squishing of text in small viewports.
- Total Staked/Unbonding Containers - adds minimum width to prevent them from becoming too small.
- Empty Table States - Adds extra padding at the top and bottom for 'Ready to explore nominations' & 'No validators in waiting' states.

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes #2104 
- Closes #2022 

#### Nominations & Payouts Table (app.tangle.tools)

https://github.com/webb-tools/webb-dapp/assets/53374218/966d4ed2-634b-47ca-bc18-13283db5f186

#### Nominations & Payouts Table (updated)

https://github.com/webb-tools/webb-dapp/assets/53374218/6b01ff14-9cd4-4fe2-a9ef-d3cb47c61221

### CODE REVIEW

**Comment by monaiuu** [comment]
quick one: fix buttons alignment for `learn more` & `join community` (horizontal alignment) 

Screenshot 2024-02-29 at 9 18 44 AM

File: apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx [hunk 1]
```diff
@@ -137,13 +137,13 @@ const NominatorStatsContainer: FC = () => {
               ) : (
                 <>
                   <Link href={WEBB_TANGLE_DOCS_STAKING_URL} target="_blank">
-                    <Button variant="utility" className="w-full">
+                    <Button variant="utility" className="!min-w-[150px]">
```
Comment (yurixander) [inline apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx:140]: Question: What's causing the need to force the `min-w` classes? Maybe we need to change `Button` component to always prioritized the classed that was passed in? 🤔

File: apps/tangle-dapp/data/DelegationsPayouts/useDelegations.ts [hunk 2]
```diff
@@ -124,7 +133,7 @@ export default function useDelegations(
       isMounted = false;
       sub?.unsubscribe();
     };
-  }, [address]);
+  }, [address, cachedNominations, setCachedNominations]);
```
Comment (yurixander) [inline apps/tangle-dapp/data/DelegationsPayouts/useDelegations.ts:136]: Won't this cause infinite `useEffect` loop, since it will re-trigger on `cachedNominations`, but then we're changing it inside by using `setCachedNominations`? I think we should be using `setCachedNominations((prev) => ...` here instead to avoid any possibility of that.

File: apps/tangle-dapp/data/DelegationsPayouts/usePayouts.ts [hunk 3]
```diff
@@ -281,7 +292,7 @@ export default function usePayouts(
       isMounted = false;
       sub?.unsubscribe();
     };
-  }, [address]);
+  }, [address, cachedPayouts, setCachedPayouts]);
```
Comment (yurixander) [inline apps/tangle-dapp/data/DelegationsPayouts/usePayouts.ts:295]: Won't this cause infinite `useEffect` loop, since it will re-trigger on `cachedPayouts `, but then we're changing it inside by using `setCachedPayouts`? I think we should be using `setCachedPayouts((prev) => ...` here instead to avoid any possibility of that.

**Review by yurixander — CHANGES_REQUESTED** [review]

**Comment by devpavan04** [comment]
@monaiuu buttons alignment

https://github.com/webb-tools/webb-dapp/assets/53374218/72aa5b96-bd35-46b4-94c4-82c8c44feb07

**Comment by drewstone** [comment]
Merge conflicts and CI (visual)
