### PR TITLE
Adds proposal table, proposal status container, fixes theme toggle and dropdown issue

### LINKED ISSUE #1502: [BUG] Dark/Light theme toggle and custom network input fields not working on stats-dapp
### Overview

- [x] Fix dark/light theme toggle not working issue on stats-dapp.

https://github.com/webb-tools/webb-dapp/assets/53374218/21855901-3685-4415-bc62-1a4a3d9d9262

- [x] Fix custom network input fields not working on stats-dapp.

https://github.com/webb-tools/webb-dapp/assets/53374218/74ab82fe-36ec-4077-bd1a-f79b4e54c596

### LINKED ISSUE #1524: [TASK] Add Proposal Table and Proposal Status to stats-dapp
### Overview
Add `Proposal Table` to `Proposal` page in `stats-dapp` to show batched proposals.

#### Proposal Status

CleanShot 2023-08-10 at 14 48 38

#### Proposal Table

CleanShot 2023-08-10 at 14 48 47

[Figma Link](https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?type=design&node-id=1174%3A150002&mode=design&t=p1NymAkny3ufEqEw-1)

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Adds `Proposal Table` to `Proposal` page to show batched proposals.
- Adds `Proposal Status` container to `Proposal` page.
- Fixes stats-dapp light/theme switch not working issue.
- Fixes stats-dapp custom network input filed not working issue.

### Proposed area of change

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [x] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes #1524 
- Closes #1502 

### Screen Recording

https://github.com/webb-tools/webb-dapp/assets/53374218/a8d6fb29-7339-4e9d-9d2b-d7bc9a1ba4e6

### CODE REVIEW

File: apps/stats-dapp/src/utils/getChipColorByProposalType.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+    }
+
+    case ProposalBatchStatus.Expired: {
+      return 'yellow';
+    }
+
+    default: {
+      throw new Error(
+        'Unknow ProposalStatus inside `getChipColorByProposalType` functioni'
+      );
```
Comment (AtelyPham) [inline apps/stats-dapp/src/utils/getChipColorByProposalType.ts:23]: Instead of throwing an error, use a default color here to prevent potential interruptions to the UI.

File: libs/icons/src/ProposalBadge/ProposalBadge.tsx [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+
+const ProposalBadge = forwardRef<SVGSVGElement, ProposalBadgeProps>(
+  ({ variant = 'Refresh', ...props }, ref) => {
+    return (
+      <svg
+        width="24"
+        height="24"
+        viewBox="0 0 24 24"
+        fill="none"
+        xmlns="http://www.w3.org/2000/svg"
```
Comment (AtelyPham) [inline libs/icons/src/ProposalBadge/ProposalBadge.tsx:77]: Add `...props` here.

File: apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx [hunk 3]
```diff
@@ -1,3 +1,341 @@
...
+
+  const pageCount = useMemo(
+    () => Math.ceil(totalItems / pageSize),
+    [pageSize, totalItems]
+  );
+
+  const data = useMemo(() => {
+    if (batchedProposals.val) {
+      const proposalIds = batchedProposals.val.items.map((item) => item.id);
+      localStorage.setItem('proposalIds', JSON.stringify(proposalIds));
```
Comment (AtelyPham) [inline apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx:192]: I'm curious as to why we need to store this info on local storage.

File: apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
Comment (AtelyPham) [inline apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx:1]: Please consider relocating the utility functions and constants to a separate file to decrease the size of the current file. A suitable location could be `apps/stats-dapp/src/containers/ProposalsTable/utils.ts`.

**Review by AtelyPham — COMMENTED** [review]
I've left some comments. Great work on this, @devpavan04! 🔥

File: apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx (hunk 3 above)
Comment (devpavan04) [reply apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx]: @AtelyPham Needed this in previous implementation to paginate between individual proposals when the proposal detail drawer is opened. I've removed it now. Might add it later if needed or if there's no workarounds to get the drawer pagination working.

**Comment by drewstone** [comment]
Are the proposal details handled in a different (future?) PR?

**Comment by devpavan04** [comment]
> Are the proposal details handled in a different (future?) PR?

Yes @drewstone different PR, current focus.
