### PR TITLE
Fix max balance and amount input error message

### LINKED ISSUE #774: [BUG] Max button don't work for wrap and deposit
## Overview
Amount input has a button to set the amount as the current account balance, this button doesn't work as expected for wrap and deposit flow

https://user-images.githubusercontent.com/35463181/205646987-fe4468bf-fe28-4204-899b-519ce1ff1dc0.mp4

### PR DESCRIPTION
**Pull request by AhmedKorim**
## Summary of changes
- Make the max button handler set the balance for the selected token (Wrappable asset for wrap & deposit,Governed asset for deposit)
- Added error message for the amount input
- disable the `Wrap and Deposit` or `Wrap` buttons for insufficient balances

### Reference issue to close (if applicable)
- Closes #774 

https://user-images.githubusercontent.com/35463181/205900558-96b3e2a6-9871-40db-98f3-d296d5a81259.mp4

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

### CODE REVIEW

**Comment by dutterbutter** [comment]
This "insufficient funds" message shouldn't have been triggered here, no?

Screen Shot 2022-12-06 at 8 17 16 AM

File: libs/evm-contracts/src/webb-vanchor.ts [hunk 1]
```diff
@@ -703,6 +703,7 @@ export class VAnchorContract {
 
     const levels = await this.inner.levels();
     const provingManager = new CircomProvingManager(wasmBuffer, levels, worker);
+    console.log('provingManager: ', provingManager);
```
Comment (dutterbutter) [inline libs/evm-contracts/src/webb-vanchor.ts:706]:
```suggestion
```

**Comment by AhmedKorim** [comment]
@dutterbutter it should be available < amount (av:2.995 vs amount :2.9956)

**Review by dutterbutter — APPROVED** [review]
