### PR TITLE
UI bug fixes bridge

### LINKED ISSUE #858: [UI-COMPONENT] Deposit flow UI changes required to align with the design
- [x]  Info icon is missing beside `SOURCE CHAIN` and `DESTINATION CHAIN` input field titles.

Expected:
Screenshot 2023-01-10 at 3 42 57 AM
Screenshot 2023-01-10 at 3 43 02 AM

Current:
Screenshot 2023-01-10 at 3 46 08 AM
Screenshot 2023-01-10 at 3 46 13 AM

- [x] `MAX` button in `AMOUNT` input field is not aligned with the design.

Expected:
Screenshot 2023-01-10 at 3 44 02 AM

Current:
Screenshot 2023-01-10 at 3 47 31 AM

- [x] `Placeholder` should not be italicized and needs padding on right for `search` icon.

Expected:
Screenshot 2023-01-10 at 3 50 57 AM
Screenshot 2023-01-10 at 3 53 29 AM

Current:
Screenshot 2023-01-10 at 3 51 05 AM
Screenshot 2023-01-10 at 3 54 10 AM

- [x] `Select Token` component's title should include selected source `chain`'s name to select token from.

Expected:
Screenshot 2023-01-10 at 3 55 30 AM

Current:
Screenshot 2023-01-10 at 3 55 48 AM

- [x] We do not need to show `Popular Tokens` title if we are not showing popular tokens in `Select Token` component.

Expected:
Screenshot 2023-01-10 at 4 00 02 AM

Current:
Screenshot 2023-01-10 at 3 58 44 AM

- [x] `BRIDGING TOKEN` input field must show both icons which makes the composition of a bridging asset.

Expected:
Screenshot 2023-01-10 at 4 02 02 AM

Current:
Screenshot 2023-01-10 at 4 01 50 AM

- [x] `Confirm Wrap & Deposit` component is missing `Confirm` text.

Expected:
Screenshot 2023-01-10 at 4 06 46 AM

Current:
Screenshot 2023-01-10 at 4 06 35 AM

- [x] `Chain Ring` component's labels are incorrect. They should be `DEPOSITING FROM` and `DEPOSITING TO`.

Expected:
Screenshot 2023-01-10 at 4 08 33 AM

Current:
Screenshot 2023-01-10 at 4 08 41 AM

- [x] `Wrapping` info is missing icons of wrapping asset's composition.

Expected:
Screenshot 2023-01-10 at 4 11 17 AM

Current:
Screenshot 2023-01-10 at 4 11 09 AM

- [x] Text inside `Chain Ring` component is not aligned with the design. We need `/` instead of `-`.

Expected:
Screenshot 2023-01-10 at 4 14 02 AM

Current:
Screenshot 2023-01-10 at 4 14 13 AM

- [x] `Depositing` info is missing `Info` icon in it's title and if wrapping, bridging token's composition token symbols are missing, only original depositing token symbol is being displayed.

Expected:
Screenshot 2023-01-10 at 4 17 06 AM

Current:
Screenshot 2023-01-10 at 4 16 59 AM

- [x] Asset icons in `Transaction Processing` component is not far enough and looks like overlapping.

Expected:
Screenshot 2023-01-10 at 5 14 51 AM

Current:
Screenshot 2023-01-10 at 5 14 29 AM

### LINKED ISSUE #860: [BUG] Dead links in transaction processing component
- [x] `Failed to deposit` in `Transaction Processing` component has two external link icons and the link takes to etherscan error page.

 Expected:
Screenshot 2023-01-10 at 5 15 03 AM

Current:
Screenshot 2023-01-10 at 5 14 40 AM

### Loom video
https://www.loom.com/share/d6dbd341159641c0a76cfe22501246b6

Tested on branch: [#850](https://github.com/webb-tools/webb-dapp/pull/850)

### LINKED ISSUE #884: [BUG] Download notes does not download the notes and is a dead dropdown option
### Overview
Download option in `Manage` dropdown is currently dead and does not download all the available notes.

### UI changes needed:
Currently the `Manage` dropdown has an option which says `Download` and it should be changed to `Download All`.

Screenshot 2023-01-12 at 4 42 41 AM

### LINKED ISSUE #896: [UI] Increase Font Size to Transaction Progress Component
## Overview
Update to increase the font sizes within transaction progress components. Please refer to the page '🟡  Transaction Progress Card' within the Figma Design System for reference. 

### Screenshot
Screenshot 2023-01-14 at 7 31 34 AM

### LINKED ISSUE #899: [TASK] Consistent file extension when downloading note
## Overview

When users note are downloaded to their desktop we should have consistency in the file extension used. Currently we download notes both in `txt` and `json`. We should make use of `json` file extension.

### Task Checklist

- [x] Remove usage of `.txt` file extension on download

### Screenshot 
file-ext

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Removes usage of `.txt` file extension to download notes.
- Deposit flow UI changes updated to align with the design.
- Fixed multiple external link issue in transaction status in transaction processing component.
- Download All now downloads the notes.
- Increases text font size in transaction processing component.

### Changes overview
https://www.loom.com/share/c38a1f72c3c24441b55a5ea26404c286

### Reference issue to close (if applicable)
- Closes #899 
- Closes #858 
- Closes #860 
- Closes #884 
- Closes #896

### CODE REVIEW

File: libs/webb-ui-components/src/components/BridgeInputs/TokenInput.tsx [hunk 1]
```diff
@@ -10,6 +11,13 @@ import { TitleWithInfo } from '../TitleWithInfo';
 import { InputWrapper } from './InputWrapper';
 import { TokenInputComponentProps } from './types';
 
+{
+  /* <TokenPairIcons
+token1Symbol={firstToken}
+token2Symbol={secondToken}
+/> */
+}
```
Comment (dutterbutter) [inline libs/webb-ui-components/src/components/BridgeInputs/TokenInput.tsx:19]: Can remove commented out code please.

**Review by dutterbutter — APPROVED** [review]
