### PR TITLE
Fixes stats slider error

### LINKED ISSUE #684: [BUG] Stats dApp slider crashes
## Overview

This task originally mentioned in https://github.com/webb-tools/webb-dapp/issues/619 outlines the stats dApp slider crashes with the following error message

```
Error: [Slider.tsx] You must provide `defaultValue` or `value` and `value.length` should less than 3 to the Slider component
    at main.3b47e0d0.js:36033:13
    at ek (873.d6e4fdc4.js:178950:359)
    at exports.unstable_runWithPriority (873.d6e4fdc4.js:179046:343)
    at fg (873.d6e4fdc4.js:178810:325)
    at Nj (873.d6e4fdc4.js:178949:308)
    at Kj (873.d6e4fdc4.js:178931:50)
    at 873.d6e4fdc4.js:178811:115
    at exports.unstable_runWithPriority (873.d6e4fdc4.js:179046:343)
    at fg (873.d6e4fdc4.js:178810:325)
    at ig (873.d6e4fdc4.js:178811:61)
```

### LINKED ISSUE #687: [QA] Checklist of fixes required for stats page
## Overview

Below is a list of items that were identified during a QA of the stats page. Items will iteratively added here throughout QA session review. 

### Task Checklist

- [x] https://github.com/webb-tools/webb-dapp/issues/669
- [x] #698 
- [x] https://github.com/webb-tools/webb-dapp/issues/685
- [x] https://github.com/webb-tools/webb-dapp/issues/684
- [x] https://github.com/webb-tools/webb-dapp/issues/686
- [x] #651
- [x] https://github.com/webb-tools/webb-dapp/issues/688

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes
- Fixes stats dApp filter slider error.

### Proposed area of change

- [ ] `apps/bridge-dapp`
- [x] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes #684 
- Closes #687 

### Screen Recording

https://user-images.githubusercontent.com/53374218/216034712-3f1eb4cf-a55d-45c9-9e7c-c4608773e248.mov

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx [hunk 1]
```diff
@@ -288,6 +289,15 @@ export const KeygenTable: FC = () => {
     [headers]
   );
 
+  const getSliderDefaultValue = (column: Column<KeygenType, unknown>) =>
```
Comment (AtelyPham) [inline apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx:292]: Consider using `useCallback` here.

**Review by AtelyPham — COMMENTED** [review]
Consider replacing `throw new Error(message)` with `console.trace(message)` in the file [Slider.tsx](https://github.com/webb-tools/webb-dapp/blob/PS/fixes-stats-slider-error/libs/webb-ui-components/src/components/Slider/Slider.tsx#L50-L52).

**Review by dutterbutter — APPROVED** [review]
