### PR TITLE
fix(tangle-dapp): Transfer modal audit

### LINKED ISSUE #2146: [TASK] 🚀 Pre-launch audit: Transfer modal
- [x] Unit shown is not correct
- [x] Show error message and disable send button when the input amount exceeds the transferrable balance
- [x] Setting the amount to the max transferrable via the `Max` button isn't compatible with the way that the amount is being displayed (ie. the precision is off)
- [x] Input accepts `e`, should only accept numbers
- [x] Disable the transfer modal's button if there is no active account
- [x] The `balances-erc20` precompile was added to allow transferring from an EVM account: https://github.com/webb-tools/tangle/pull/580, implement the ability to transfer when an EVM account is active
- [x] Test that sending Substrate -> Substrate works
- [x] Test that sending Substrate -> EVM works (recipient address is a **Substrate** address)
- [x] Test that sending Substrate -> EVM works (recipient address is an **EVM** address)
- [ ] Test that sending EVM -> Substrate works
- [x] Test that sending EVM -> EVM works
- [x] The amount input shows an error message immediately upon opening the modal, because the value is empty
- [x] The `Send` button should be disabled if the inputs have errors
- [x] Disable the transfer modal's trigger button if the active account's transferrable balance is zero
- [x] During a transfer tx, if the balance sent drops the available balance < to the balance sent, it'll 'optimistically' report a 'not enough available' error BEFORE the modal closes. Fix this by disabling inputs & error checking during transaction processing
- [x] When performing a Substrate transfer, sometimes the transaction itself succeeds, but the UI stays loading likely caused by an error:
  ```
  app-index.js:35 Error: Cannot convert 'Token' via asModule
    at eval (Enum.js:172:27)
    at Type.get [as asModule] (property.js:24:24)
    at extractErrorFromTxStatus
  ```

### LINKED ISSUE #2183: [TASK] Remove services from non-local development dApp state
The `Services` dropdown should not be visible on non-development environments because it is not ready yet.

### PR DESCRIPTION
**Pull request by yurixander**
## Summary of changes

_Provide a detailed description of proposed changes._

- [ ] ⚠️ **NOT IMPLEMENTED IN THIS PR**: Test that sending EVM -> Substrate works
  - Running into issues with address conversion, specifically for this case, will likely handle it in a different issue/PR.
- [x] Unit shown is not correct
- [x] Show error message and disable send button when the input amount exceeds the transferrable balance
- [x] Setting the amount to the max transferrable via the `Max` button isn't compatible with the way that the amount is being displayed (ie. the precision is off)
- [x] Input accepts `e`, should only accept numbers
- [x] Disable the transfer modal's button if there is no active account
- [x] The `balances-erc20` precompile was added to allow transferring from an EVM account: https://github.com/webb-tools/tangle/pull/580, implement the ability to transfer when an EVM account is active
- [x] Test that sending Substrate -> Substrate works
- [x] Test that sending Substrate -> EVM works (recipient address is a **Substrate** address)
- [x] Test that sending Substrate -> EVM works (recipient address is an **EVM** address)
- [x] Test that sending EVM -> EVM works
- [x] The amount input shows an error message immediately upon opening the modal, because the value is empty
- [x] The `Send` button should be disabled if the inputs have errors
- [x] Disable the transfer modal's trigger button if the active account's transferrable balance is zero
- [x] During a transfer tx, if the balance sent drops the available balance < to the balance sent, it'll 'optimistically' report a 'not enough available' error BEFORE the modal closes. Fix this by disabling inputs & error checking during transaction processing
- [x] When performing a Substrate transfer, sometimes the transaction itself succeeds, but the UI stays loading likely caused by an error:
  ```
  app-index.js:35 Error: Cannot convert 'Token' via asModule
    at eval (Enum.js:172:27)
    at Type.get [as asModule] (property.js:24:24)
    at extractErrorFromTxStatus
  ```

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2146
- Closes #2183

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/101931215/3cd37589-ff18-4185-b276-9f362f5fe543

https://github.com/webb-tools/webb-dapp/assets/101931215/44e340ba-f46b-44ff-868c-eed59b0d3723

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: apps/tangle-dapp/utils/evm/createTangleViemChainFromNetwork.ts [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+      name: currencyName,
+      symbol: currencySymbol,
+      decimals: 18,
+    },
+    blockExplorers: {
+      default: {
+        name: blockExplorerName,
+        // TODO: Need to ensure that this will work as expected and not cause issues? Is it fine to default to the Polkadot explorer for a Viem chain?
+        // Default to the Polkadot explorer if the EVM explorer URL is not set.
+        url: network.evmExplorerUrl ?? network.polkadotExplorerUrl,
```
Comment (vutuanlinh2k2) [inline apps/tangle-dapp/utils/evm/createTangleViemChainFromNetwork.ts:36]: Is it required here? I think default to `polkadotExplorerUrl` is not a good option here

File: apps/tangle-dapp/components/AddressInput2/AddressInput2.tsx [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+  type: AddressType;
+  showPasteButton?: boolean;
+  value: string;
+  isDisabled?: boolean;
+  baseInputOverrides?: Partial<BaseInputProps>;
+  setValue: (newValue: string) => void;
+  setErrorMessage?: (error: string | null) => void;
+};
+
+const AddressInput2: FC<AddressInput2Props> = ({
```
Comment (vutuanlinh2k2) [inline apps/tangle-dapp/components/AddressInput2/AddressInput2.tsx:29]: change name or add comments here for further explanation

File: apps/tangle-dapp/components/AmountInput2/AmountInput2.tsx [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+  showMaxAction?: boolean;
+  amount: BN | null;
+  isDisabled?: boolean;
+  baseInputOverrides?: Partial<BaseInputProps>;
+  errorOnEmptyValue?: boolean;
+  setAmount: (newAmount: BN | null) => void;
+  setErrorMessage?: (error: string | null) => void;
+};
+
+const AmountInput2: FC<AmountInput2Props> = ({
```
Comment (vutuanlinh2k2) [inline apps/tangle-dapp/components/AmountInput2/AmountInput2.tsx:25]: same as [here](https://github.com/webb-tools/webb-dapp/pull/2185/files#r1553494627)

**Review by monaiuu — APPROVED** [review]

**Review by vutuanlinh2k2 — APPROVED** [review]
