### PR TITLE
Fixes connected label in chain selection component

### LINKED ISSUE #697: [BUG] connected network loses the `connected` label
**Describe the bug**
Opening the chain selection from the header button, don't show the `connected` label
**To Reproduce**
1. Go to the bridge UI, with a wallet/chain selected
2. Click on bridge select source chain, The selection view shows with the connected chain has the label `connected`
3. Click on the header button to switch chains, the connected chain doesn't have the `connected` label

**Expected behavior**
Chian selection from the header should indicate the connected chain with the `connected` label

**Screenshots**

https://user-images.githubusercontent.com/35463181/202226360-4f340df5-94a5-407e-811f-4ef75e2dc1c5.mp4

**Additional context**
This was discovered from #683

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes
- Chain selection component now shows connected label when opened through chain switcher button.

## Changes overview

https://user-images.githubusercontent.com/53374218/213808447-c1662fe2-b3b0-4825-a0f3-69acb066d167.mov

### Reference issue to close (if applicable)
- Closes #697

### CODE REVIEW

File: apps/bridge-dapp/src/components/Header/ChainSwitcherButton.tsx [hunk 1]
```diff
@@ -31,6 +31,10 @@ export const ChainSwitcherButton: FC = () => {
     });
   }, [chains]);
 
+  // useEffect(() => {
```
Comment (drewstone) [inline apps/bridge-dapp/src/components/Header/ChainSwitcherButton.tsx:34]: Can be removed

**Review by drewstone — CHANGES_REQUESTED** [review]
LG, don't forget to remove commented out codes when they're not needed.

**Review by drewstone — APPROVED** [review]
