### PR TITLE
Use PolkadotAPI to show live chain data and Bug fixes in stats-dapp

### LINKED ISSUE #1262: [BUG] Time calculation is based on UTC
The UI uses UTC time to perform calculations, this ends up producing wrong assumptions in the UI. aka a proposal signed right now will show as signed X hours before.

Proposal signed just a minute before:
Screenshot 2023-05-24 at 5 01 33 PM

### LINKED ISSUE #1419: [TASK] Standardize time display format across applications
## Description
Currently, our applications lack a standardized format for displaying time, leading to potential confusion and reduced usability. To enhance the user experience and ensure consistency, lets standardize the time display format throughout the application. 

### Proposed Solution
- Implement `date-fns`, a JavaScript date utility library, to standardize time display. ([link](https://date-fns.org/docs/Getting-Started))
- Note: we need to define a standard format for displaying time AND relative time using the formatting options provided by date-fns. 

### Screenshot
Image

### LINKED ISSUE #1514: [BUG] Stats dApp network thresholds don't always load
## Expected Behavior
The stats dApp thresholds should load. The block number / finalized block number loads immediately, what's stopping us from using the same API to make other data load?

### Current Behavior
image

### Possible Solution
Use the chain API directly. Improve the RPC connections / recommend load balancing. Propose solutions.

### LINKED ISSUE #1559: Tx hash links to webb.tools; this should be updated.
### Overview

`txhash` in `keys` details page of `stats-dapp` should link to explorer and not to `webb.tools`.

https://github.com/webb-tools/webb-dapp/assets/53374218/ac6094a0-d815-464b-9daa-8edf5975ee31

### LINKED ISSUE #1563: [BUG] Fix Proposal Table Incorrect Data
### Overview
Proposal Batch table currently displays data incorrectly - proposal batches are not in order. Investigate if this issue is related to subquery backend or could be fixed in stats-dapp frontend.

### Screenshots

CleanShot 2023-08-23 at 10 43 12

CleanShot 2023-08-23 at 10 43 32

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

The current version of `stats-dapp` does not display data if `subquery indexing` isn't updated to the latest block. To address this, this PR enhances `stats-dapp` by integrating it with the `PolkadotAPI`. This allows the dapp to fetch live chain data directly, significantly reducing the presence of loaders in the application. As a result, users can view crucial data without waiting for the indexing to catch up to the most recent block.

Additionally, this PR resolves related bugs. Notably, it ensures that the `batched proposals` and `keys` tables are dynamically updated as subquery indexing progresses.

### Proposed area of change

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [x] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes #1514 
- Closes #1563 
- Closes #1559 
- Closes #1419 
- Closes #1262 

### Screenshots

CleanShot 2023-08-24 at 13 07 32

CleanShot 2023-08-24 at 13 09 06

CleanShot 2023-08-24 at 13 10 49

### Screen Recording

https://github.com/webb-tools/webb-dapp/assets/53374218/82e1881e-eeec-4a27-a09c-4d3504e3d2a8

### CODE REVIEW

File: apps/stats-dapp/src/containers/KeyStatusCardContainer/KeyStatusCardContainer.tsx [hunk 1]
```diff
@@ -1,57 +1,47 @@
...
+  const { val: blocksData } = useBlocks();
 
-  const activeKeyData = useMemo(() => {
-    return {
-      key: currentKey?.compressed,
-      session: Number(currentKey?.session),
-    };
-  }, [data, currentKey]);
+  const showDetails = useMemo(() => {
+    if (blocksData?.finalized - blocksData?.latestIndexedBlock < 5) {
```
Comment (AtelyPham) [inline apps/stats-dapp/src/containers/KeyStatusCardContainer/KeyStatusCardContainer.tsx:24]: Before performing calculations on two potentially undefined values, you should first check if either value is undefined.

```tsx
if (blocksData && blocksData.finalized - blocksData.lastestIndexedBlock < 5)
```

File: apps/stats-dapp/src/pages/Authorities.tsx [hunk 2]
```diff
@@ -74,7 +67,7 @@ const columns: ColumnDef<UpcomingThreshold, any>[] = [
     ),
 
     cell: (props) => {
-      const authorities = props.getValue<DiscreteList>();
+      const authorities = props.getValue();
```
Comment (AtelyPham) [inline apps/stats-dapp/src/pages/Authorities.tsx:70]: Add a type for the authorities variable here.

File: apps/stats-dapp/src/pages/Authorities.tsx [hunk 3]
```diff
@@ -98,51 +91,54 @@ const Authorities = () => {
...
+  }, [keygenThreshold, signatureThreshold]);
 
-  const data = useMemo(
-    () => (upComingThresholds ? Object.values(upComingThresholds) : []),
-    [upComingThresholds]
-  );
+  const data = useMemo(() => {
+    return [
+      {
+        stats: 'Next',
```
Comment (AtelyPham) [inline apps/stats-dapp/src/pages/Authorities.tsx:125]: `stats: 'Next' as const,`

File: apps/stats-dapp/src/pages/Authorities.tsx [hunk 4]
```diff
@@ -98,51 +91,54 @@ const Authorities = () => {
...
+        session: String(currentSessionNumber + 1),
+        keyGen: keygenThreshold,
+        signature: signatureThreshold,
```
Comment (AtelyPham) [inline apps/stats-dapp/src/pages/Authorities.tsx:128]: keyGen: keygenThreshold.toString(),
signature: signatureThreshold.toString(),

File: apps/stats-dapp/src/provider/hooks/useAuthorities.ts
Comment (AtelyPham) [inline apps/stats-dapp/src/provider/hooks/useAuthorities.ts:1]: This file contains numerous non-null assertions, `variable!`. It would be beneficial if you could incorporate type checking to prevent these non-null assertions, as this could help reduce the likelihood of bugs.

Additionally, another issue found in this file is the error: `Cannot find name 'DiscreteList'.`.

File: libs/dapp-config/src/wallets/wallets-config.tsx [hunk 5]
```diff
@@ -118,7 +118,7 @@ export const walletsConfig: Record<number, WalletConfig> = {
     homeLink: 'https://walletconnect.com/',
     connector: new WalletConnectConnector({
       options: {
-        projectId: process.env['BRIDGE_DAPP_WALLET_CONNECT_PROJECT_ID'] ?? '',
```
Comment (AtelyPham) [inline libs/dapp-config/src/wallets/wallets-config.tsx:121]: Revert this change, please.

**Review by AtelyPham — COMMENTED** [review]
Left some comments.

**Comment by devpavan04** [comment]
@AtelyPham 

- Proposal Batch Table Fix

https://github.com/webb-tools/webb-dapp/assets/53374218/b901ddbc-b1fd-4510-8f8c-5e86bcc8cd82

- Key Detail Page - tx hash is now block hash

https://github.com/webb-tools/webb-dapp/assets/53374218/42f97910-e7ff-488b-9edc-0aa0c802f8bd

- Time Format Bug Fix in Key Detail Page

https://github.com/webb-tools/webb-dapp/assets/53374218/dd5f7b50-8fa8-462e-ac84-2330130a15c8

File: libs/webb-ui-components/src/constants/index.ts [hunk 6]
```diff
@@ -60,6 +60,8 @@ export const WEBB_DAPP_NEW_ISSUE_URL =
 export const WEBB_FAUCET_URL = 'https://faucet.webb.tools/';
 export const STATS_DOCUS_URL =
   'https://docs.webb.tools/docs/projects/stats-dapp/overview/';
+export const POLKADOT_EXPLORER_URL =
+  'https://polkadot.js.org/apps/?rpc=wss://tangle-standalone-archive.webb.tools#/explorer/query/';
```
Comment (AtelyPham) [inline libs/webb-ui-components/src/constants/index.ts:64]: The current setup is satisfactory for the time being. However, we should aim for a dynamic configuration based on the currently selected RPC. Please refer to the following links for more information:

- [populateBlockExplorer](https://github.com/webb-tools/webb-dapp/blob/6bad94a740ec2dcd63b139e4a33e878610609f90/libs/dapp-config/src/chains/substrate/index.tsx#L5-L14) in the Polkadot UI.
- [How to calculate the URL for a given block hash in the Polkadot UI](https://github.com/webb-tools/webb-dapp/blob/edb92734e13134fd9ebe1a678aa4b5f6c5b8caf7/libs/api-provider-environment/src/transaction/useTransactionQueue.tsx#L44-L47).

**Review by AtelyPham — APPROVED** [review]
Just a small comment, I'll create an issue for it. Otherwise, LGTM 👍 Great work on this @devpavan04 🔥
