### PR TITLE
Fix current major issues on Hubble Stats

### LINKED ISSUE #1609: [BUG] Hubble Stats Overview Page Does Not Update with Latest Data
Currently, the Overview Page of Hubble Stats does not update with the latest data. It only displays data from the time of deployment. This issue may be related to the NX project configuration and the Netlify run command. Further investigation is required.

## Expected Behavior
The Overview Page should continuously update with the latest data.

### Current Behavior
The Overview Page only displays data from the time of deployment and does not update with the latest data.

### LINKED ISSUE #1625: [BUG] Deposit data does not get updated on Hubble Stats in local environment + Make sure all transactions data recorded on both local and live chains
When testing with the **local** environment (local Orbit networks, Hubble Bridge, and Hubble Stats), the **deposit** data across components on Hubble Stats is not updated after making a deposit in the Bridge. 

Expected behavior: 
- Data on Hubble Stats should be updated after performing actions on the Hubble Bridge
- Test on other actions as well: **Withdraw** and **Transfer**

Notes:
- This behavior works fine on live Orbit Chains at the moment
- Need to check back all the components related to transactions, deposits, and withdraws

### LINKED ISSUE #1627: [TASK] UI Update on Hubble Stats
### Pool Tables First column
Lots of dead space in the first column on Pool Overview and Pool Wrapping Tables. The first column should be capped max at a certain percentage of the whole width. Note: make sure UI works on all the screen sizes.

Image

### Make Pool Overview Card smaller
The Pool Overview Card is too big if there are big numbers inside, need to move the percentage below:

**New Design:**
Image

### Change Table Header (no need this anymore)
All headers of the tables on both the home page and detail page should have colors different from the rows. cc @monaiuu to update this in Figma and add new images below here

Suggestion:
- dark theme: header color **lighter** than row's color
- light theme: **darker**

### LINKED ISSUE #1646: [TASK] Implement Transition State between Overview and Detail Page in Hubble Stats
Currently in Hubble Stats, when users click on a row in Shielded Tables to navigate to Pool Detail page, it takes some time to load without any loading indicator.

**Solution**: Add a Spinner to let the user know the page is currently loading.

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes
_Provide a detailed description of proposed changes._
- 

### Proposed area of change
_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [x] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes #1609 
- Closes #1625 
- Closes #1627 
- Closes #1646

### Screen Recording
_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/836e6af5-dc54-40ef-8eb8-7973f5874cdc

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: apps/hubble-stats/components/charts/types.ts [hunk 1]
```diff
@@ -27,3 +27,18 @@ export interface VolumeChartProps
     withdrawal: number;
   }>;
 }
+
+export interface ChartTooltipContentProps {
+  date: Date;
+  info: Array<{
+    color: string;
```
Comment (drewstone) [inline apps/hubble-stats/components/charts/types.ts:34]: Spacing is off

**Review by drewstone — APPROVED** [review]
LG some touch up on spacing.

File: apps/hubble-stats/components/charts/types.ts (hunk 1 above)
Comment (vutuanlinh2k2) [reply apps/hubble-stats/components/charts/types.ts:34]: The CI for Clean/Lint runs fine @drewstone!

File: apps/hubble-stats/app/pool/[slug]/page.tsx
Comment (AtelyPham) [inline apps/hubble-stats/app/pool/[slug]/page.tsx:1]: Is there any reason why don't you use the [loading.tsx](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming#instant-loading-states) file instead of `Suspense`?

**Review by AtelyPham — COMMENTED** [review]
Left a comment, otherwise LGTM 👍

File: apps/hubble-stats/app/pool/[slug]/page.tsx
Comment (vutuanlinh2k2) [reply apps/hubble-stats/app/pool/[slug]/page.tsx:1]: If I add loading.tsx there will be 2 same file, one for overview and one for detail page. In the future we might want to add suspense to each component in each page for better performance, so loading.tsx will eventually be deleted by then!

**Comment by monaiuu** [comment]
@vutuanlinh2k2 unable to review UI updates from preview link due to no pool display in table. 

Screenshot 2023-09-20 at 6 29 39 PM

**Comment by AtelyPham** [comment]
@monaiuu This is the latest deployment preview [link](https://650b2f7f639d2f0008e49a1a--hubble-stats.netlify.app/).

**Comment by vutuanlinh2k2** [comment]
> @vutuanlinh2k2 unable to review UI updates from preview [link](https://github.com/webb-tools/webb-dapp/pull/1651) due to no pool display in table.
> 
> Screenshot 2023-09-20 at 6 29 39 PM

The back-end is ready by now, please check back the deploy link again @monaiuu

**Review by monaiuu — APPROVED** [review]
