### PR TITLE
Fix Page Switching Performance

### LINKED ISSUE #2126: [TASK] 🚀 Pre-launch audit: Page switching performance is slow
# Overview
When I click, I want to go to that page not wait.
https://www.loom.com/share/d1a79031bb814c7a9372fb35993a3ac0?sid=d480a95f-8f11-4448-8dfd-7a6fa92f0837

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes

_Provide a detailed description of proposed changes._

- Fix page Switching Performance (Account, Nominations and Claim pages)
- Minor UI updates on Key Stats Container on Nominations page
- Update Breadcrumb icon for Nomination page

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2126 

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/3d736c1d-a9d5-4a9f-9178-d74cc8fec367

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by vutuanlinh2k2** [comment]
cc @1xstj @AtelyPham it seems the backend for Leaderboard is down at the moment

File: apps/tangle-dapp/app/page.tsx [hunk 1]
```diff
@@ -9,16 +9,30 @@ const AccountPage: FC = () => {
...
 
       <Typography variant="h4" fw="bold">
         Manage Balances
       </Typography>
 
-      <BalancesTableContainer />
+      <Suspense fallback={<SkeletonLoader className="rounded-2xl h-[190px]" />}>
+        <BalancesTableContainer />
+      </Suspense>
     </div>
```
Comment (yurixander) [inline apps/tangle-dapp/app/page.tsx:36]: These components already utilize skeleton loaders underneath.. if we add this here we might have too many skeleton loaders? Hmm

Comment (vutuanlinh2k2) [reply apps/tangle-dapp/app/page.tsx:36]: You can check the replay to see if the UI is still good or not. I find this still acceptable

**Review by yurixander — APPROVED** [review]
