### PR TITLE
Hubble Stats: Fix Bugs in Pool Wrapping Table

### LINKED ISSUE #1626: [BUG] Pool Wrapping Table: Duplicate tokens in pool composition + Wrong token symbol for each row
1. When testing with local chains, there's an error with the pool composition since one token can **appear twice** on the Pool Wrapping Table component. Each token should appear **only once** on every pool composition.

2. The **unit** on each row on the Pool Wrapping Table should be the token symbol that the row represents, not the fungible token.

Image

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes
_Provide a detailed description of proposed changes._
- Fix duplicate tokens in composition
- Update currency for each row
- Update constant to handle data from local chains

### Proposed area of change
_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [x] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes #1626 

### Screen Recording
_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/43aa0b94-dd6c-47a2-80e1-82e4b8b5044b

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: apps/hubble-stats/components/Breadcrumbs/Breadcrumbs.tsx [hunk 1]
```diff
@@ -10,50 +10,43 @@ import {
...
-    const poolAddress = parts[2];
-    // if invalid poolAddress, the breadcrumb only show the default item
-    if (!VANCHORS_MAP[poolAddress]) {
-      activeItem = '';
-    } else {
-      activeItem = VANCHORS_MAP[poolAddress].fungibleTokenName;
+  const breadCrumbs = useMemo<BreadcrumbType[]>(() => {
+    // check if current path is /pool/<poolAddress>
+    if (parts.length === 3 && parts[0] === '' && parts[1] === 'pool') {
+      const poolAddress = parts[2];
```
Comment (AtelyPham) [inline apps/hubble-stats/components/Breadcrumbs/Breadcrumbs.tsx:22]: I believe it would be more prudent to use a more reliable method than array syntax `[]` to obtain the pool address. If the structure of the pathname changes, the current implementation could fail. In this instance, a regular expression (regex) might be a more robust solution.

**Review by AtelyPham — COMMENTED** [review]
Left a comment, otherwise LG 👍
