### PR TITLE
Fixes upload spend note dead link and no spend note message

### LINKED ISSUE #942: [UI-COMPONENTS] Update no notes found message
### Overview
Update the message in available spend notes and shielded assets table when there is no notes found to match with the design.

Expected(Available spend notes):
Screenshot 2023-01-30 at 3 58 07 AM

Current(Available spend notes):
Screenshot 2023-01-30 at 3 58 15 AM

Expected(Shielded assets):
Screenshot 2023-01-30 at 3 57 24 AM

Current(Shielded assets):
Screenshot 2023-01-30 at 3 57 36 AM

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes
- Updates no spend notes available message
- Fixes Upload spend notes dead link  

### Changes video

https://user-images.githubusercontent.com/53374218/215608682-2b194db4-4122-4d34-9162-d414b26e50a7.mov

 
### Reference issue to close (if applicable)
- Closes #942

### CODE REVIEW

**Comment by dutterbutter** [comment]
@devpavan04 we should add [this](https://github.com/marketplace/actions/check-links-with-linkcheck) link checker to the CI. Thoughts?

File: apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx [hunk 1]
```diff
@@ -260,8 +260,8 @@ export const ShieldedAssetsTableContainer: FC<
   if (!data.length) {
     return (
       <EmptyTable
-        title="No assets found"
-        description="Don't see your assets?"
+        title="No spend notes found"
+        description="Your notes are stored locally as you transact and encrypted on-chain for persistent storage. Don’t see your spend note?"
```
Comment (dutterbutter) [inline apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx:264]:
```suggestion
        description="Notes are stored locally and encrypted on-chain. Can't find spend note?"
```

File: apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx [hunk 2]
```diff
@@ -180,7 +180,7 @@ export const SpendNotesTableContainer: FC<SpendNotesTableContainerProps> = ({
     return (
       <EmptyTable
         title="No spend notes found"
-        description="Don't see your spend note?"
+        description="Your notes are stored locally as you transact and encrypted on-chain for persistent storage. Don’t see your spend note?"
```
Comment (dutterbutter) [inline apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx:183]:
```suggestion
        description="Notes are stored locally and encrypted on-chain. Can't find spend note?"
```

**Review by dutterbutter — CHANGES_REQUESTED** [review]
LGTM just change the copy a bit.

**Review by dutterbutter — APPROVED** [review]
