### PR TITLE
Leaderboard UI fix

### LINKED ISSUE #1956: [CHECKLIST] Fixes to Leaderboard
- [ ] Match top nav to tangle.tools.
- [ ] Remove Request Points BTN
- [ ] Update Footer Link for Twitter to `https://twitter.com/tangle_network`
- [ ] Update Documentation link to `https://docs.tangle.tools`
- [ ] Update Source Code Link to `https://github.com/webb-tools/tangle`
- [ ] Update Whitepaper Link to `https://github.com/webb-tools/tangle/blob/main/Tangle_Network_Whitepaper_V1.pdf`
- [ ] Update Brand Kit Link to `https://www.tangle.tools/press-kit`
- [ ] Do the same for the visual icon social buttons at bottom.

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes

_Provide a detailed description of proposed changes._

- Minor UI and Links fix for Tangle Leaderboard

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/tangle-dapp`
- [x] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. Closes #233)._

- Closes #1956 

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/6e69a8ef-5bda-4574-bdcc-dfb751b8cdd7

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by yurixander — APPROVED** [review]
👍🏼

File: apps/testnet-leaderboard/components/CountdownSection/CTAButtons.tsx [hunk 1]
```diff
@@ -2,26 +2,14 @@
...
+      <Button href={GUIDELINES_URL} target="_blank" className="px-5 md:px-9">
         View Guidelines
       </Button>
-      <Button
-        href={REQUEST_POINTS_URL}
-        target="_blank"
-        className="px-5 md:px-9"
-      >
-        Request Points
-      </Button>
```
Comment (AtelyPham) [inline apps/testnet-leaderboard/components/CountdownSection/CTAButtons.tsx:24]: I believe we should modify this button to read `Join Discord` instead of removing it.

**Review by AtelyPham — APPROVED** [review]
