### PR TITLE
 Pre-launch audit: Show vesting info on Claim Airdrop page + Fix Flicker problem when successfully claimed

### LINKED ISSUE #2170: [TASK] 🚀 Pre-launch audit: Show vesting info on Claim Airdrop page + Fix Flicker problem when successfully claimed
### Description
- Show information about vesting schedule amount + liquid amount on the Claim Airdrop page
- Flicker problem when claiming:  after claiming successfully, the page state changed to not eligible ,then go to Claim Success page, the page should be navigated to the success page right away

https://github.com/webb-tools/webb-dapp/assets/69841784/6fe5bbcd-467d-4522-8df9-435da51ce0fe

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes

_Provide a detailed description of proposed changes._

- Showing Free & Vesting Balance in Claim page
- Fix Flicker problem after successfully claimed
- Remove hover state on Checkbox component, it is unecessary and causes bad UI

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2170 

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/66364b00-8fc1-4969-b6aa-db294c2cdddc

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: apps/tangle-dapp/app/claim/EligibleSection.tsx [hunk 1]
```diff
@@ -221,9 +223,26 @@ const EligibleSection: FC<Props> = ({
...
+                  totalAmount.sub(vestingAmount),
+                  nativeTokenSymbol
+                )}`}{' '}
+                will be available immediately as free balance.
+              </Typography>
+
+              {/* Vesting */}
+              <Typography variant="body1" fw="bold" ta="center">
+                {`${formatTokenBalance(vestingAmount, nativeTokenSymbol)}`} will
+                be vested over 24 months w/ a 1 month cliff.
```
Comment (monaiuu) [inline apps/tangle-dapp/app/claim/EligibleSection.tsx:242]: with a 1 month cliff.

File: apps/tangle-dapp/app/claim/EligibleSection.tsx [hunk 2]
```diff
@@ -206,13 +208,13 @@ const EligibleSection: FC<Props> = ({
           />
         </div>
 
-        <div className="flex flex-col gap-4 p-4 border rounded-xl border-mono-0 dark:border-mono-180 shadow-[0px_4px_8px_0px_rgba(0,0,0,0.08)] bg-glass dark:bg-glass_dark">
+        <div className="space-y-6 p-4 border rounded-xl border-mono-0 dark:border-mono-180 shadow-[0px_4px_8px_0px_rgba(0,0,0,0.08)] bg-glass dark:bg-glass_dark">
           <Typography variant="body1" fw="bold" ta="center">
-            You will receive the liquid balance of...
+            You will receive the total liquid balance of...
```
Comment (monaiuu) [inline apps/tangle-dapp/app/claim/EligibleSection.tsx:213]: remove 'liquid'. 

(the term [liquid](https://docs.tangle.tools/docs/tokenomics/allocation/#initial-liquid-tokens) can be confused as the initial free balance)

**Review by drewstone — APPROVED** [review]
