### PR TITLE
Fix Sidebar not keep consistent state when refreshing pages

### LINKED ISSUE #1629: [BUG] Hubble Stats sidebar not remain consistent when refresh
The sidebar expands and then collapses when users refresh the page:

**Expected behavior**: The sidebar should remain consistent when user refresh

https://github.com/webb-tools/webb-dapp/assets/69841784/38503214-7851-40d9-91da-a1eb81631602

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes
_Provide a detailed description of proposed changes._
- Utilizing NextJS Cookies and Server Actions to handle sidebar state

### Proposed area of change
_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [x] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes #1629 

### Screen Recording
_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/60f98b8c-d2b3-4a10-be62-7a25c82a9eba

-----

### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: apps/hubble-stats/containers/Layout/Layout.tsx [hunk 1]
```diff
@@ -1,13 +1,23 @@
-import React, { type FC, type PropsWithChildren } from 'react';
+import React, { type PropsWithChildren } from 'react';
+import { cookies } from 'next/headers';
 import { Footer } from '@webb-tools/webb-ui-components';
 
 import { HeaderChipsContainer } from '..';
 import { Breadcrumbs, SideBar, SideBarMenu } from '../../components';
 
-const Layout: FC<PropsWithChildren> = ({ children }) => {
+export default async function Layout({ children }: PropsWithChildren) {
```
Comment (AtelyPham) [inline apps/hubble-stats/containers/Layout/Layout.tsx:8]: Consider removing unnecessary `async` here.

**Review by AtelyPham — APPROVED** [review]
