### PR TITLE
fixes invalid note upload error

### LINKED ISSUE #941: [BUG] Handle invalid spend note uploads
### Overview
Currently the bridge dApp crashes when an invalid spend note is uploaded to the note account and we should handle the error and notify user about the error.

### Error
Screenshot 2023-01-29 at 3 41 00 PM

### Issue video

https://user-images.githubusercontent.com/53374218/215363059-70d66c3c-4177-4998-bbc3-515bb22edc38.mov

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes
- Catches invalid note upload error and notifies the user about the invalid note upload.

### Proposed area of change

- [x] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes #941 

### Screen Recording

https://user-images.githubusercontent.com/53374218/216020524-14d4ccd0-36df-4d7c-92a1-cb6f7e99d997.mov

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: apps/bridge-dapp/src/containers/UploadSpendNoteModal/UploadModalContent.tsx [hunk 1]
```diff
@@ -58,6 +58,15 @@ export const UploadModalContent: FC<UploadModalContentProps> = ({
   // useMemo for note size
   const noteSize = useMemo(() => Object.keys(notes).length, [notes]);
 
+  // Parse JSON string
+  const parseJSON = (str: string) => {
```
Comment (AtelyPham) [inline apps/bridge-dapp/src/containers/UploadSpendNoteModal/UploadModalContent.tsx:62]: Please consider using `useCallback` here, also adding document for the return type of this function.

**Review by dutterbutter — APPROVED** [review]
