### PR TITLE
Fix duplicate notifications

### LINKED ISSUE #444: [BUG] When switching networks through the DApp, the notification fires twice
**Describe the bug**

https://user-images.githubusercontent.com/16654909/175097972-8bc788f0-ebe8-477e-a86d-eba993df9d8e.mov

**Expected behavior**
There should only be one notification.

**Additional context**
We should make sure provider instances are properly cleaned up when switching as well.

### PR DESCRIPTION
**Pull request by AhmedKorim**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?
Duplicate notifications appeared for web3 provider
Issue Number: Closes #444 

## What is the new behavior?
The notification shows now only once

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

https://user-images.githubusercontent.com/35463181/182423195-b2852fa0-6543-49c3-b6b4-79ab84aa449f.mp4

### CODE REVIEW

File: packages/react-environment/src/WebbProvider.tsx [hunk 1]
```diff
@@ -84,7 +84,7 @@ const getDefaultBridge = (chain: Chain, bridgeConfig: Record<number, BridgeConfi
 
   return undefined;
 };
-
+let count = 0;
```
Comment (AtelyPham) [inline packages/react-environment/src/WebbProvider.tsx:87]: Unused variable

**Review by nepoche — APPROVED** [review]

**Review by AtelyPham — APPROVED** [review]
LGTM 👍 Resolve conflict and ready to be merged.
