### PR TITLE
Fix prev session's active period incorrect progress bar

### LINKED ISSUE #1605: [BUG] Prev session's active period progress bar is incorrect in key detail page
### Overview

In the `stats-dapp` key details page, the progress bar for the session prior to the current one is not displaying as full, even though all previous sessions should have completed their active periods. This means that, except for the current session, every other session's progress bar should be at 100%. Investigate why the session before current session's active period progress bar is not full.

CleanShot 2023-09-11 at 06 39 37

CleanShot 2023-09-11 at 06 40 00

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Fixes previous session's active period incorrect progress bar. This issue occurs only when a session rotation happens soon after (not after session height) previous session rotation block (maybe like 10 -15 blocks after prev session rotation block).
- We should show full progress bar for all the previous keys other than current key. This PR fixes that.

### Proposed area of change

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [x] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes #1605 

### Screenshots

**Current Key**:

CleanShot 2023-09-28 at 14 51 11

**Previous key before fix**:

CleanShot 2023-09-28 at 14 51 30

**Previous key after fix (Progress bar is full)**:

CleanShot 2023-09-28 at 14 53 07

### CODE REVIEW

File: apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx [hunk 1]
```diff
@@ -64,6 +77,22 @@ export const KeyDetail = forwardRef<HTMLDivElement, KeyDetailProps>(
     );
     const time = useSubQLtime();
 
+    useEffect(() => {
+      const isKeyMatch =
+        keysList && keysList.length > 1 && keysList[1] === keyId;
+
+      if (isKeyMatch && latestKeyDetail?.start && keyDetail?.start) {
+        const latestKeyStartTime =
+          new Date(latestKeyDetail.start).getTime() / 1000;
```
Comment (drewstone) [inline apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx:86]: Spacing is off here @devpavan04

**Review by drewstone — APPROVED** [review]
Please format the code, otherwise looks good
