### PR TITLE
fix: fix account explorer link in wallet dropdown

### LINKED ISSUE #2247: [BUG] Account dropdown's `Open Explorer` icon links to an empty page
This should link to Subscan/accounts, and it needs to consider the active network as well.

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes

_Provide a detailed description of proposed changes._

- Modify `useTxExplorerUrl` to `useExplorerUrl` for both `tx` and `address` use
- Handle correct `accountExplorerUrl` in `WalletDropdown` component

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2247 

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/9321114c-c44b-4810-9ca3-1f2236897825

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: apps/tangle-dapp/data/restaking/useRestakingProfile.ts [hunk 1]
```diff
@@ -31,19 +28,7 @@ const useRestakingProfile = (address?: string) => {
   }, [ledgerOpt]);
 
   const totalRestaked = useMemo(
```
Comment (vutuanlinh2k2) [inline apps/tangle-dapp/data/restaking/useRestakingProfile.ts:30]: @AtelyPham I removed this code because I think the unit should be unified. Feel free to give me reasons why you were adding this check when implementing the restaking page

**Review by AtelyPham — APPROVED** [review]
