### PR TITLE
Stats dApp fixes and adds rotated key status to key timeline

### LINKED ISSUE #1260: [BUG] Key rotation height is not consistent
The key rotation is shown in the `keys` page is not correct. It does not match the last session rotation block as reflected in the chain.

## Expected Behavior
Session 80 rotated at block 29555
Screenshot 2023-05-24 at 4 59 25 PM

### Current Behavior
UI shows session 80 rotated at block 29097
Screenshot 2023-05-24 at 4 59 20 PM

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Adds `Rotated` status to key `Timeline` component in `Key Details` page.
- Adds a spinner to `Authorities Table` when in loading state.
- Now `Keygen Table` in `Authority Detail` page shows `Public Key` value.

### Proposed area of change

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [x] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes #1260 

### Screen Recording

https://github.com/webb-tools/webb-dapp/assets/53374218/844a3bd6-d0e5-46a6-9967-395b248f1926

CleanShot 2023-08-31 at 11 07 00

### CODE REVIEW

File: apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx [hunk 1]
```diff
@@ -200,6 +201,10 @@ export const AuthoritiesTable: FC<AuthoritiesTableProps> = ({
     getFilteredRowModel: getFilteredRowModel(),
   });
 
+  const tableIsLoading = useMemo(() => {
```
Comment (AtelyPham) [inline apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx:204]: Why don't we utilize the `isLoading` boolean which is returned by the `useAuthorities` hook.

**Review by AtelyPham — COMMENTED** [review]
Left a comment.

**Review by vutuanlinh2k2 — APPROVED** [review]
Other than Tin's comment, LGTM!
